pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-flask-app"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('my-app') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker rm -f flask-container || true'
                sh 'docker run -d -p 5000:5000 --name flask-container $IMAGE_NAME'
            }
        }
    }

    post {
        success {
            echo "✅ App deployed: http://<jenkins-server-ip>:5000"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}

